### ISSUE TITLE
Less than obvious error if no environment variables set

### ISSUE THREAD

**Issue by foolswood** [Lantero/vcdriver#7]
You get this:
```
Traceback (most recent call last):
  File "/home/dave/work/full_stack_tests/py2venv/lib/python2.7/site-packages/vcdriver/vm.py", line 83, in create
    connection(), vim.VirtualMachine, self.template
  File "/lib/python2.7/site-packages/vcdriver/session.py", line 34, in connection
    sslContext=context
  File "/lib/python2.7/site-packages/pyVim/connect.py", line 817, in SmartConnect
    sslContext)
  File "/lib/python2.7/site-packages/pyVim/connect.py", line 702, in __FindSupportedVersion
    sslContext)
  File "/lib/python2.7/site-packages/pyVim/connect.py", line 622, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/lib/python2.7/site-packages/pyVim/connect.py", line 583, in __GetElementTree
    conn = http_client.HTTPSConnection(server, port=port, **kwargs)
  File "/usr/lib64/python2.7/httplib.py", line 1258, in __init__
    source_address)
  File "/usr/lib64/python2.7/httplib.py", line 751, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib64/python2.7/httplib.py", line 783, in _get_hostport
    i = host.rfind(':')
AttributeError: 'NoneType' object has no attribute 'rfind'

```

**Comment by Lantero** [comment]
True, I'll try to find a way of making that more user-friendly

**Comment by foolswood** [comment]
Unless you object I was going to have a fiddle and see if I can come up with something.

**Comment by Lantero** [comment]
Version 3.0.0 comes with a refactor of the configuration. Certain functions now have special `configurable` arguments that can be passed as:
- A keyword argument
- Environment variable
- A INI configuration file
If the values cannot be found in any of those, a clear exception will be raised, listing the missing parameters and explaining how to pass them.

I'll update the wiki soon :slightly_smiling_face:
